In [6]:
import os

from collections import deque
from six import next
from box import Box

import torch
from scipy.sparse import lil_matrix

from dataset import GraphRecDataset
from model import GraphRecModel

In [3]:
args = {
    ##############datasets###############
    'data_path' : '/opt/ml/input/data/train/',
    'test_ratio' : 0.2,
    'use_exist' : True, # test_ratio 바꾸면 한번 False 처리해서 다시 불러와야함!
    'is_graph' : True,

    'use_side_information' : True,
    'side_titles' : False, # Not implement yet
    'side_genres' : True,
    'side_directors' : False, # Not implement yet
    'side_writers' : False, # Not implement yet
    'side_years' : True,
    
    #############optimizer###############
    'lr' : 2e-4,
    'wd' : 0.00,
    
    ##############model##################
    'user_weight' : 0.08,
    'movie_weight' : 0.06,
    'mf_size' : 50,
    
    ##############trainer#################
    'batch_size' : 256,
    'epochs' : 200,
    
}
args = Box(args)

dirs = {
    'ratings' : os.path.join(args.data_path, 'train_ratings.csv'),
    'titles' : os.path.join(args.data_path, 'titles.tsv'),
    'genres' : os.path.join(args.data_path, 'genres.tsv'),
    'directors' : os.path.join(args.data_path, 'directors.tsv'),
    'years' : os.path.join(args.data_path, 'years_new.tsv'),
    'writers' : os.path.join(args.data_path, 'writers.tsv'),
    'output' : './output/',
    'model_output' : './model'
}
dirs = Box(dirs)

In [4]:
dataset = GraphRecDataset(args, dirs)

load existing train graphs!
load train side information...
load existing inference graphs!
load inference side information...


In [7]:
model = GraphRecModel(args, dataset)

AttributeError: 'GraphRecDataset' object has no attribute 'n_feature_user'

In [8]:
dataset.n_

In [4]:
############# ML 100k dataset ###########

BATCH_SIZE = 1000
PERC=0.9
USER_NUM = 943
ITEM_NUM = 1682
#df_train, df_test = get_data100k()

#Without Graph Feature
MFSIZE=40
UW=0.08
IW=0.06
LR=0.0002
EPOCH_MAX = 601
#tf.reset_default_graph()
#GraphRec(df_train, df_test,ItemData=False,UserData=False,Graph=False,Dataset='100k')

#With Graph Features
MFSIZE=50
UW=0.05
IW=0.02
LR=0.00003
EPOCH_MAX = 196

In [18]:
import numpy as np
from tqdm import tqdm

In [21]:
class GraphRecModel() :
    def __init__(self, dataset):
        
        # data initialize
        self.train_data = dataset.train_data
        self.test_data = dataset.test_data
        self.user_num = dataset.n_users
        self.movie_num = dataset.n_movies

In [22]:
model = GraphRecModel(dataset)

100%|██████████| 4123577/4123577 [07:39<00:00, 8981.92it/s]

[[1. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [1. 1. 0. ... 0. 0. 0.]]
